# Generated by Django 4.2.4 on 2023-08-30 09:29

import app.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_cartitem'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
                ('objects', app.manager.UserManager()),
            ],
        ),
    ]
