# Generated by Django 4.2.4 on 2023-08-30 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_rename_created_at_order_date_ordered_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='date_ordered',
        ),
    ]
