# Generated by Django 4.2.4 on 2023-08-30 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_order_date_ordered'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='books',
            new_name='book',
        ),
    ]
